apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: platform-api-vault-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao-svc.admin.svc.cluster.local:8200"
    roleName: "platform-role"
    objects: |
      - objectName: "DATABASE_URL"
        secretPath: "secret/data/platform/api"
        secretKey: "DATABASE_URL"
      - objectName: "REDIS_URL"
        secretPath: "secret/data/platform/api"
        secretKey: "REDIS_URL"
      - objectName: "KEYCLOAK_INTERNAL_URL"
        secretPath: "secret/data/platform/api"
        secretKey: "KEYCLOAK_INTERNAL_URL"
      - objectName: "KEYCLOAK_REALM"
        secretPath: "secret/data/platform/api"
        secretKey: "KEYCLOAK_REALM"
      - objectName: "KEYCLOAK_CLIENT_ID"
        secretPath: "secret/data/platform/api"
        secretKey: "KEYCLOAK_CLIENT_ID"
      - objectName: "KEYCLOAK_CLIENT_SECRET"
        secretPath: "secret/data/platform/api"
        secretKey: "KEYCLOAK_CLIENT_SECRET"
      - objectName: "GITLAB_URL"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_URL"
      - objectName: "GITLAB_TOKEN"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_TOKEN"
      - objectName: "GITLAB_GROUP"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_GROUP"
      - objectName: "GITLAB_TENANT_REPO"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_TENANT_REPO"
      - objectName: "GITLAB_REGISTRY_PATH"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_REGISTRY_PATH"
      - objectName: "GITLAB_PROJECT_ID"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_PROJECT_ID"
      - objectName: "GITLAB_DEFAULT_BRANCH"
        secretPath: "secret/data/platform/api"
        secretKey: "GITLAB_DEFAULT_BRANCH"
      - objectName: "ARGOCD_URL"
        secretPath: "secret/data/platform/api"
        secretKey: "ARGOCD_URL"
      - objectName: "ARGOCD_TOKEN"
        secretPath: "secret/data/platform/api"
        secretKey: "ARGOCD_TOKEN"
      - objectName: "KUBE_API_URL"
        secretPath: "secret/data/platform/api"
        secretKey: "KUBE_API_URL"
      - objectName: "KUBE_TOKEN"
        secretPath: "secret/data/platform/api"
        secretKey: "KUBE_TOKEN"
      - objectName: "API_SECRET_KEY"
        secretPath: "secret/data/platform/api"
        secretKey: "API_SECRET_KEY"
