apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-vault-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao-svc.admin.svc.cluster.local:8200"
    roleName: "platform-role"
    objects: |
      - objectName: "POSTGRES_DB"
        secretPath: "secret/data/platform/postgres"
        secretKey: "POSTGRES_DB"
      - objectName: "POSTGRES_USER"
        secretPath: "secret/data/platform/postgres"
        secretKey: "POSTGRES_USER"
      - objectName: "POSTGRES_PASSWORD"
        secretPath: "secret/data/platform/postgres"
        secretKey: "POSTGRES_PASSWORD"
  secretObjects:
  - secretName: postgres-secret
    type: Opaque
    data:
    - objectName: "POSTGRES_DB"
      key: POSTGRES_DB
    - objectName: "POSTGRES_USER"
      key: POSTGRES_USER
    - objectName: "POSTGRES_PASSWORD"
      key: POSTGRES_PASSWORD
