apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.tenant_id }}-vault-secrets
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao-svc.admin.svc.cluster.local:8200"
    roleName: "tenant-role"
    objects: |
      {{- if .Values.services.gitlab.enabled }}
      - objectName: "gitlab-secret"
        secretPath: "secret/data/tenants/{{ .Values.tenant_id }}/oidc"
        secretKey: "gitlab_secret"
      {{- end }}
      {{- if .Values.services.jenkins.enabled }}
      - objectName: "jenkins-secret"
        secretPath: "secret/data/tenants/{{ .Values.tenant_id }}/oidc"
        secretKey: "jenkins_secret"
      {{- end }}
      {{- if .Values.services.nexus.enabled }}
      - objectName: "nexus-secret"
        secretPath: "secret/data/tenants/{{ .Values.tenant_id }}/oidc"
        secretKey: "nexus_secret"
      - objectName: "nexus-proxy-cookie"
        secretPath: "secret/data/tenants/{{ .Values.tenant_id }}/oidc"
        secretKey: "nexus_proxy_cookie"
      {{- end }}
  secretObjects:
  - secretName: "{{ .Values.tenant_id }}-secrets"
    type: Opaque
    data:
    {{- if .Values.services.gitlab.enabled }}
    - objectName: "gitlab-secret"
      key: "gitlab-oidc-client-secret"
    {{- end }}
    {{- if .Values.services.jenkins.enabled }}
    - objectName: "jenkins-secret"
      key: "jenkins-oidc-client-secret"
    {{- end }}
    {{- if .Values.services.nexus.enabled }}
    - objectName: "nexus-secret"
      key: "nexus-oidc-client-secret"
    - objectName: "nexus-proxy-cookie"
      key: "nexus-oauth2-proxy-cookie-secret"
    {{- end }}
